export const SEARCH_GIPHY = 'SEARCH_GIPHY';
export const SEARCH_GIPHY_SUCCESS = 'SEARCH_GIPHY_SUCCESS';
export const SEARCH_GIPHY_FAIL = 'SEARCH_GIPHY_FAIL';

export const FETCH_TRENDING = 'FETCH_TRENDING';
export const FETCH_TRENDING_FAIL = 'FETCH_TRENDING_FAIL';
export const FETCH_TRENDING_SUCCESS = 'FETCH_TRENDING_SUCCESS';